master:
  build: spark
  command: /spark/bin/spark-class org.apache.spark.deploy.master.Master
  hostname: master
  mem_limit: 4g
  cpuset: "0,1"
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8091:8080

zookeeper:
  image: jplock/zookeeper
  hostname: zookeeper
  mem_limit: 4g
  cpuset: "0,1"
  expose:
    - 2181
    - 2888
    - 3888
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
  links:
    - master

kafka: 
  image: digitalwonderland/kafka:latest
  hostname: kafka
  mem_limit: 4g
  environment: 
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_BROKER_ID: -1
    KAFKA_ADVERTISED_HOST_NAME: kafka
  cpuset: "0,1"
  expose: 
    - 9092
  ports: 
    - 9092:902
  links:
    - master
    - zookeeper

worker:
  build: spark
  command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  mem_limit: 4g
  cpuset: "0,1"
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 4g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
